### ISSUE TITLE
Cloudflare has been enabled on the website

### ISSUE THREAD

**Issue by daddywolf** [vxwong/spain-visa-monitor#9]
I've realised that Cloudflare protection has been enabled on the website. The script cannot be used properly. Anybody can solve this issue？

**Comment by michaelh151** [comment]
This module might help. [https://github.com/VeNoMouS/cloudscraper](url)

**Comment by daddywolf** [comment]
Problem solved.

**Comment by daddywolf** [comment]
The technical problem has been solved. However, bypassing anti-bot technology is illegal and the code will not be made public.
